### ISSUE TITLE
Hang

### ISSUE THREAD

**Issue by GoogleCodeExporter** [XianglinLi/opendedup#11]
```
I don't know how to reproduce this reliably.  After heavy use for several
hours SDFS 0.8.14 is hung.  All file system calls just hang, and it uses
lots of CPU (looks like one thread hogs the CPU core constantly and many
more use about 5-15% each, totaling 150% to 300% of four cores).  Here are
the last log messages.  The hang probably occured several hours after the
last message:

Apr 7, 2010 8:58:26 PM org.opendedup.sdfs.io.SparseDedupFile updateMap
SEVERE: unable to write [B@6233170a
java.io.IOException: hashtable
[/opt/sdfs/sdfs_vol1/ddb/e3/e35c4f17-182d-4932-8998-8e66682ce9a6/e35c4f17-182d-4
932-8998-8e66682ce9a6.map]
is close
        at
org.opendedup.collections.LongByteArrayMap.put(LongByteArrayMap.java:205)
        at
org.opendedup.sdfs.io.SparseDedupFile.updateMap(SparseDedupFile.java:297)
        at
org.opendedup.sdfs.io.SparseDedupFile.writeCache(SparseDedupFile.java:238)
        at
org.opendedup.sdfs.io.WritableCacheBuffer.close(WritableCacheBuffer.java:314)
        at org.opendedup.util.PoolThread.run(PoolThread.java:29)
Apr 7, 2010 8:58:26 PM org.opendedup.sdfs.io.SparseDedupFile writeCache
SEVERE: unable to add chunk [[B@82dc3e4] at position 14024704
java.io.IOException: java.io.IOException: hashtable
[/opt/sdfs/sdfs_vol1/ddb/e3/e35c4f17-182d-4932-8998-8e66682ce9a6/e35c4f17-182d-4
932-8998-8e66682ce9a6.map]
is close
        at
org.opendedup.sdfs.io.SparseDedupFile.updateMap(SparseDedupFile.java:300)
        at
org.opendedup.sdfs.io.SparseDedupFile.writeCache(SparseDedupFile.java:238)
        at
org.opendedup.sdfs.io.WritableCacheBuffer.close(WritableCacheBuffer.java:314)
        at org.opendedup.util.PoolThread.run(PoolThread.java:29)
Apr 7, 2010 8:58:26 PM org.opendedup.sdfs.io.WritableCacheBuffer close
SEVERE: Error while closing
java.io.IOException: unable to add chunk [[B@27059fa1] at position 14811136
because java.io.IOException: java.io.IOException: hashtable
[/opt/sdfs/sdfs_vol1/ddb/e3/e35c4f17-182d-4932-8998-8e66682ce9a6/e35c4f17-182d-4
932-8998-8e66682ce9a6.map]
is close
        at
org.opendedup.sdfs.io.SparseDedupFile.writeCache(SparseDedupFile.java:249)
        at
org.opendedup.sdfs.io.WritableCacheBuffer.close(WritableCacheBuffer.java:314)
        at org.opendedup.util.PoolThread.run(PoolThread.java:29)
Apr 7, 2010 8:58:26 PM org.opendedup.sdfs.io.WritableCacheBuffer close
SEVERE: Error while closing
java.io.IOException: unable to add chunk [[B@82dc3e4] at position 14024704
because java.io.IOException: java.io.IOException: hashtable
[/opt/sdfs/sdfs_vol1/ddb/e3/e35c4f17-182d-4932-8998-8e66682ce9a6/e35c4f17-182d-4
932-8998-8e66682ce9a6.map]
is close
        at
org.opendedup.sdfs.io.SparseDedupFile.writeCache(SparseDedupFile.java:249)
        at
org.opendedup.sdfs.io.WritableCacheBuffer.close(WritableCacheBuffer.java:314)
        at org.opendedup.util.PoolThread.run(PoolThread.java:29)
java.lang.IllegalArgumentException: error while closing
java.io.IOException: unable to add chunk [[B@82dc3e4] at position 14024704
because java.io.IOException: java.io.IOException: hashtable
[/opt/sdfs/sdfs_vol1/ddb/e3/e35c4f17-182d-4932-8998-8e66682ce9a6/e35c4f17-182d-4
932-8998-8e66682ce9a6.map]
is close
        at
org.opendedup.sdfs.io.WritableCacheBuffer.close(WritableCacheBuffer.java:318)
        at org.opendedup.util.PoolThread.run(PoolThread.java:29)
java.lang.IllegalArgumentException: error while closing
java.io.IOException: unable to add chunk [[B@184ea4ac] at position 14417920
because java.io.IOException: java.io.IOException: hashtable
[/opt/sdfs/sdfs_vol1/ddb/e3/e35c4f17-182d-4932-8998-8e66682ce9a6/e35c4f17-182d-4
932-8998-8e66682ce9a6.map]
is close
        at
org.opendedup.sdfs.io.WritableCacheBuffer.close(WritableCacheBuffer.java:318)
        at org.opendedup.util.PoolThread.run(PoolThread.java:29)
java.lang.IllegalArgumentException: error while closing
java.io.IOException: unable to add chunk [[B@64f6594] at position 14286848
because java.io.IOException: java.io.IOException: hashtable
[/opt/sdfs/sdfs_vol1/ddb/e3/e35c4f17-182d-4932-8998-8e66682ce9a6/e35c4f17-182d-4
932-8998-8e66682ce9a6.map]
is close
        at
org.opendedup.sdfs.io.WritableCacheBuffer.close(WritableCacheBuffer.java:318)
        at org.opendedup.util.PoolThread.run(PoolThread.java:29)
java.lang.IllegalArgumentException: error while closing
java.io.IOException: unable to add chunk [[B@1e52812e] at position 14680064
because java.io.IOException: java.io.IOException: hashtable
[/opt/sdfs/sdfs_vol1/ddb/e3/e35c4f17-182d-4932-8998-8e66682ce9a6/e35c4f17-182d-4
932-8998-8e66682ce9a6.map]
is close
        at
org.opendedup.sdfs.io.WritableCacheBuffer.close(WritableCacheBuffer.java:318)
        at org.opendedup.util.PoolThread.run(PoolThread.java:29)
java.lang.IllegalArgumentException: error while closing
java.io.IOException: unable to add chunk [[B@1d61185a] at position 14155776
because java.io.IOException: java.io.IOException: hashtable
[/opt/sdfs/sdfs_vol1/ddb/e3/e35c4f17-182d-4932-8998-8e66682ce9a6/e35c4f17-182d-4
932-8998-8e66682ce9a6.map]
is close
        at
org.opendedup.sdfs.io.WritableCacheBuffer.close(WritableCacheBuffer.java:318)
        at org.opendedup.util.PoolThread.run(PoolThread.java:29)
java.lang.IllegalArgumentException: error while closing
java.io.IOException: unable to add chunk [[B@27059fa1] at position 14811136
because java.io.IOException: java.io.IOException: hashtable
[/opt/sdfs/sdfs_vol1/ddb/e3/e35c4f17-182d-4932-8998-8e66682ce9a6/e35c4f17-182d-4
932-8998-8e66682ce9a6.map]
is close
        at
org.opendedup.sdfs.io.WritableCacheBuffer.close(WritableCacheBuffer.java:318)
        at org.opendedup.util.PoolThread.run(PoolThread.java:29)
Apr 7, 2010 11:43:17 PM org.opendedup.sdfs.filestore.OpenFileMonitor run
WARNING: Unable check files
java.lang.NullPointerException
        at
org.opendedup.sdfs.filestore.OpenFileMonitor.isFileStale(OpenFileMonitor.java:94
)
        at
org.opendedup.sdfs.filestore.OpenFileMonitor.run(OpenFileMonitor.java:59)
        at java.lang.Thread.run(Thread.java:717)

```

Original issue reported on code.google.com by `stur...@gmail.com` on 8 Apr 2010 at 7:59

**Comment by GoogleCodeExporter** [comment]
```
After umount (not an easy task, btw) and remount, a lot of my file system is 
corrupt
and SFDS keeps saying:

Apr 8, 2010 12:10:14 PM org.opendedup.sdfs.io.MetaDataDedupFile mashal
SEVERE: unable to find metafile for [filename]
Exception in thread "Thread-4" java.lang.Error: CRITICAL: page header magic for 
block
309465919 not OK 0
        at jdbm.recman.PageHeader.<init>(PageHeader.java:74)
        at jdbm.recman.TranslationPage.<init>(TranslationPage.java:69)
        at jdbm.recman.TranslationPage.getTranslationPageView(TranslationPage.java:81)
        at jdbm.recman.LogicalRowIdManager.update(LogicalRowIdManager.java:118)
        at jdbm.recman.LogicalRowIdManager.insert(LogicalRowIdManager.java:96)
        at jdbm.recman.CacheRecordManager.insert(CacheRecordManager.java:199)
        at jdbm.btree.BTree._insert(BTree.java:837)
        at jdbm.btree.BPage.<init>(BPage.java:225)
        at jdbm.btree.BTree.insert(BTree.java:349)
        at org.opendedup.sdfs.filestore.MetaFileStore.setMetaFile(MetaFileStore.java:262)
        at org.opendedup.sdfs.filestore.MetaFileStore.getMF(MetaFileStore.java:144)
        at fuse.SDFS.SDFSFileSystem.getattr(SDFSFileSystem.java:164)
        at fuse.Filesystem3ToFuseFSAdapter.getattr(Filesystem3ToFuseFSAdapter.java:59)

```

Original comment by `stur...@gmail.com` on 8 Apr 2010 at 12:33

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `sam.silv...@gmail.com` on 9 Apr 2010 at 2:48
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
sturles,

What the SDFS volume full? It that the possible underlying issue here? Let me 
know,
it will help me fix the issue.
```

Original comment by `sam.silv...@gmail.com` on 9 Apr 2010 at 2:57

**Comment by GoogleCodeExporter** [comment]
```
Fixing file corruption issue.Looks like, since the metafile database was not 
closed
correctly it did not correctly persist the file metadata.
```

Original comment by `sam.silv...@gmail.com` on 9 Apr 2010 at 4:26

**Comment by GoogleCodeExporter** [comment]
Original comment by `sam.silv...@gmail.com` on 15 Apr 2010 at 3:31
- Changed state: **Verified**
