### ISSUE TITLE
More symlink troubles

### ISSUE THREAD

**Issue by GoogleCodeExporter** [XianglinLi/opendedup#21]
```
Here is an interesting error.  It is from the latest version running on Debian. 
 I hope sdfs isn't trying to do anything with the data in the file or device 
the symlink points to?:

16:39:44.091 Thread-949851 FATAL [sdfs]: unable to de-serialize 
/opt/sdfs/current/files/flu-ts01/home/x/.wine/dosdevices/d::
java.io.StreamCorruptedException: invalid stream header: 00000000
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:298)
    at org.opendedup.sdfs.io.MetaDataDedupFile.getFile(MetaDataDedupFile.java:242)
    at org.opendedup.sdfs.filestore.MetaFileStore.getMF(MetaFileStore.java:95)
    at fuse.SDFS.SDFSFileSystem.utime(SDFSFileSystem.java:479)
    at fuse.Filesystem3ToFuseFSAdapter.utime(Filesystem3ToFuseFSAdapter.java:261)
16:39:44.099 Thread-949851 ERROR [fuse.SDFS.SDFSFileSystem]: 
java.lang.NullPointerException
java.lang.NullPointerException
    at org.opendedup.sdfs.filestore.MetaFileStore.cacheMF(MetaFileStore.java:63)
    at org.opendedup.sdfs.filestore.MetaFileStore.getMF(MetaFileStore.java:96)
    at fuse.SDFS.SDFSFileSystem.utime(SDFSFileSystem.java:479)
    at fuse.Filesystem3ToFuseFSAdapter.utime(Filesystem3ToFuseFSAdapter.java:261)

hypatia:/backup/current# ls -l flu-ts01/home/x/.wine/dosdevices/d::
lrwxrwxrwx 1 root root 8 23 aug.  16:39 flu-ts01/home/x/.wine/dosdevices/d:: -> 
/dev/sdb

```

Original issue reported on code.google.com by `stur...@gmail.com` on 24 Aug 2010 at 7:06

**Comment by GoogleCodeExporter** [comment]
```
Is resolving all the symlink issues on the agenda?  I'm not sure if SDFS safe 
to my system when people link to all kinds of files and devices.
```

Original comment by `stur...@gmail.com` on 8 Sep 2010 at 9:37

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I've installed sdfs 1.0.0 on Ubuntu 10.10 (x86_64) and I'm also having problems 
with symlinks - although I don't get any java exceptions. It just won't let you 
create a valid symlink to any file which doesn't exist. A file is created, but 
it shows up with a bunch of ??? beside it in a directory listing. It doesn't 
matter if the target file resides on or off the sdfs file system, the link 
still appears invalid and can't be removed. If the target file is created then 
the link will list as a valid symlink and removal will become possible.

```

Original comment by `james.ho...@gmail.com` on 26 Nov 2010 at 1:03

**Comment by GoogleCodeExporter** [comment]
```
same here, after trying to backup a linux host with symlinks the whole 
directory is not more accessible:

 WARN [Thread-11] (MetaFileStore.java:209) - delete failed : unable to delete [/backup/files/mail/bin]
ERROR [Thread-12] (SDFSFileSystem.java:271) - unable to read path /mail



any ideas how to resolve it? switch to tar.gz backups for linux hosts destroys 
the whole idea -.-
```

Original comment by `maikomku...@gmail.com` on 9 Mar 2012 at 5:44

**Comment by GoogleCodeExporter** [comment]
```
here the whole message:

fuse.FuseException
        at fuse.SDFS.SDFSFileSystem.getFtype(SDFSFileSystem.java:625)
        at fuse.SDFS.SDFSFileSystem.getdir(SDFSFileSystem.java:268)
        at fuse.Filesystem3ToFuseFSAdapter.getdir(Filesystem3ToFuseFSAdapter.java:117)
FATAL [Thread-11] (MetaDataDedupFile.java:259) - unable to de-serialize 
/backup/files/mail/bin/netcat
java.io.StreamCorruptedException: invalid stream header: 7F454C46
        at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
        at java.io.ObjectInputStream.<init>(Unknown Source)
        at org.opendedup.sdfs.io.MetaDataDedupFile.getFile(MetaDataDedupFile.java:254)
        at org.opendedup.sdfs.filestore.MetaFileStore.getMF(MetaFileStore.java:100)
        at org.opendedup.sdfs.filestore.MetaFileStore.removeMetaFile(MetaFileStore.java:220)
        at org.opendedup.sdfs.filestore.MetaFileStore.removeMetaFile(MetaFileStore.java:206)
        at org.opendedup.sdfs.filestore.MetaFileStore.removeMetaFile(MetaFileStore.java:206)
        at fuse.SDFS.SDFSFileSystem.rmdir(SDFSFileSystem.java:472)
        at fuse.Filesystem3ToFuseFSAdapter.rmdir(Filesystem3ToFuseFSAdapter.java:175)
 WARN [Thread-11] (MetaFileStore.java:209) - delete failed : unable to delete [/backup/files/mail/bin/netcat]
 WARN [Thread-11] (MetaFileStore.java:209) - delete failed : unable to delete [/backup/files/mail/bin]
```

Original comment by `maikomku...@gmail.com` on 9 Mar 2012 at 5:45

**Comment by GoogleCodeExporter** [comment]
```
Same issue present for SDFS 1.1.5 on Debian wheezy/sid.
Kernel Version: 3.2.0-2-amd64

2012-06-13 20:57:39,430 [Thread-11] FATAL sdfs  - unable to de-serialize 
/path/to/file
java.io.StreamCorruptedException: invalid stream header: 7F454C46
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:298)
        at org.opendedup.sdfs.io.MetaDataDedupFile.getFile(MetaDataDedupFile.java:254)
        at org.opendedup.sdfs.filestore.MetaFileStore.getMF(MetaFileStore.java:100)
        at fuse.SDFS.SDFSFileSystem.utime(SDFSFileSystem.java:570)
        at fuse.Filesystem3ToFuseFSAdapter.utime(Filesystem3ToFuseFSAdapter.java:280)

```

Original comment by `theevila...@gmail.com` on 14 Jun 2012 at 7:31

**Comment by GoogleCodeExporter** [comment]
```
I am investigating this for 1.1.6 release
```

Original comment by `sam.silv...@gmail.com` on 14 Jun 2012 at 6:28
- Changed state: **Accepted**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Also - when snapshotting a symlink, it follows the symlink rather than creating 
a symlink in the snapshot.
```

Original comment by `markridl...@googlemail.com` on 18 Jun 2012 at 1:16

**Comment by GoogleCodeExporter** [comment]
```
I'm getting the follow error while trying to copy a symlink to the sdfs:
cp: cannot create symbolic link `/mnt/sdfs-test/home/dfl/data': No such file or 
directory

I'm using version 1.2.1-2 and Centos 6 64bit.
```

Original comment by `peteryw...@gmail.com` on 31 Jan 2013 at 9:36

**Comment by GoogleCodeExporter** [comment]
```
Running sdfs-1.2.1_amd64 from .deb package on Debian Testing, I experienced an 
issue  when trying opendedup for my backup storage.

As I often do system backups and it's been about a year since I've used sdfs, I 
was copying my existing backup data to a new sdfs volume and let it run for 
about 8 hours or so to see how the deduplication ratio would be.

I woke up this morning to find that w, which, less, and many of my favorite 
gnutils on the OS disk had been replaced with opendeup metadata as it had used 
my "real" files rather than storing the symlinks.

Are you guys planning to keep this method of following symlinks?

I'm currently going across all my filesystems to see if there is any data 
missing outside of my OS disk. :(
```

Original comment by `theevila...@gmail.com` on 10 Feb 2013 at 10:05
