### ISSUE TITLE
NullPointerException from SparseDedupFile.forceClose() when ESXi 4 VM starts on NFS mounted SDFS volume

### ISSUE THREAD

**Issue by GoogleCodeExporter** [XianglinLi/opendedup#31]
```
What steps will reproduce the problem?
1. Run a vSphere 4.0 VM on ESXi using an NFS datastore. The datastore is 
pointing to an Ubuntu 10.04 LTS server sharing an SDFS volume over NFS.

What is the expected output? What do you see instead?

I'm getting this exception:

java.lang.NullPointerException
        at org.opendedup.sdfs.io.SparseDedupFile.forceClose(SparseDedupFile.java:553)
        at org.opendedup.sdfs.io.SparseDedupFile.delete(SparseDedupFile.java:158)
        at org.opendedup.sdfs.filestore.MetaFileStore.removeMetaFile(MetaFileStore.java:195)
        at fuse.SDFS.SDFSFileSystem.unlink(SDFSFileSystem.java:489)
        at fuse.Filesystem3ToFuseFSAdapter.unlink(Filesystem3ToFuseFSAdapter.java:150)

What version of the product are you using? On what operating system?

SDFS 1.0.0 on Ubuntu 10.04 LTS.

Please provide any additional information below.

The exception occurs as soon as the VM starts running.

```

Original issue reported on code.google.com by `james.ho...@gmail.com` on 26 Nov 2010 at 3:32

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I'm not sure if it makes any difference or not, but the ESXi VM was an Ubuntu 
10.10 server. I was also able to reproduce the error on a secondary data .vmdk 
stored on a different SDFS volume. The first SDFS volume (boot disk) was 
created with --io-chunk-size 4 and the second SDFS volume was created with 
--io-chunk-size 32. 

The data .vmdk file was created using:

setfattr -n user.cmd.vmdk.make -v 5556:vm-data:10GB .

The exception occurred in the data volume's console output while copying a 
bunch of files from the boot .vmdk to the data .vmdk. The VM then had a kernel 
panic and several of these lines were dumped into the /var/log/messages file:

Nov 25 22:48:22 vm-data kernel: [    1.040671] pci 0000:00:17.6: BAR 13: can't 
allocate I/O resource [0x10000-0xffff]

I'm not sure if the kernel lockup is related to the exception, or is just 
coincidence.

```

Original comment by `james.ho...@gmail.com` on 26 Nov 2010 at 4:54

**Comment by GoogleCodeExporter** [comment]
```
I think the issue is you need to set the safe-close=false within the SDFS 
config file. NFS does a lot of file open and close which cause issues with SDFS 
IO. Setting safe-close=false fixes issues with NFS.
```

Original comment by `sam.silv...@gmail.com` on 8 Dec 2010 at 1:00
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
No I have safe-close=false set in the config. I'd read about the NFS issues, so 
whatever's causing the exception can't be that.
```

Original comment by `james.ho...@gmail.com` on 8 Dec 2010 at 7:32
