### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [XianglinLi/opendedup#5]
```
During mv of a large (14739 files in 4617 directories) tree, theese errors
suddenly started running over my screen and SDFS never recovered.  Version
0.8.11 on Debian:

java.io.FileNotFoundException:
/opt/sdfs/sdfs_vol1/ddb/ce/ce49c4ec-fe31-42c6-8562-9a97e5bd97f3/ce49c4ec-fe31-42
c6-8562-9a97e5bd97f3.map
(Too many open files)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:233)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:118)
        at
org.opendedup.collections.LongByteArrayMap.openFile(LongByteArrayMap.java:130)
        at
org.opendedup.collections.LongByteArrayMap.<init>(LongByteArrayMap.java:38)
        at
org.opendedup.sdfs.io.SparseDedupFile.initDB(SparseDedupFile.java:598)
        at
org.opendedup.sdfs.io.SparseDedupFile.writeCache(SparseDedupFile.java:187)
        at
org.opendedup.sdfs.io.SparseDedupFile.writeCache(SparseDedupFile.java:178)
        at
org.opendedup.sdfs.io.SparseDedupFile.close(SparseDedupFile.java:482)
        at
org.opendedup.sdfs.io.SparseDedupFile.unRegisterChannel(SparseDedupFile.java:458
)
        at
org.opendedup.sdfs.io.DedupFileChannel.close(DedupFileChannel.java:287)
        at fuse.SDFS.SDFSFileSystem.release(SDFSFileSystem.java:207)
        at
fuse.Filesystem3ToFuseFSAdapter.release(Filesystem3ToFuseFSAdapter.java:338)
12:20:13.746 Thread-18731 ERROR [fuse.SDFS.SDFSFileSystem]:
java.lang.NullPointerException
java.lang.NullPointerException
        at fuse.SDFS.SDFSFileSystem.getattr(SDFSFileSystem.java:113)
        at
fuse.Filesystem3ToFuseFSAdapter.getattr(Filesystem3ToFuseFSAdapter.java:59)
12:20:13.762 Thread-18733 ERROR [fuse.SDFS.SDFSFileSystem]:
java.lang.NullPointerException
java.lang.NullPointerException
        at fuse.SDFS.SDFSFileSystem.getattr(SDFSFileSystem.java:113)
        at
fuse.Filesystem3ToFuseFSAdapter.getattr(Filesystem3ToFuseFSAdapter.java:59)
12:20:13.763 Thread-18731 ERROR [fuse.SDFS.SDFSFileSystem]:
java.lang.NullPointe
rException
java.lang.NullPointerException
        at fuse.SDFS.SDFSFileSystem.getattr(SDFSFileSystem.java:113)
        at
fuse.Filesystem3ToFuseFSAdapter.getattr(Filesystem3ToFuseFSAdapter.java:59)
java.io.FileNotFoundException:
/opt/sdfs/sdfs_vol1/ddb/ba/ba918985-04d8-4187-a85e-7af42a86d226/ba918985-04d8-41
87-a85e-7af42a86d226.chk
(Too many open files)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:233)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:118)
[...]

Also this type:
java.io.FileNotFoundException:
/backup/sdfs/sdfs_vol1/files/andeby/home/anfotux/.openoffice.org/3/user/registry
/data/org/openoffice/Office/Views.xcu
(Too many open files)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:201)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:95)
        at java.io.FileWriter.<init>(FileWriter.java:63)
        at
org.opendedup.sdfs.io.MetaDataDedupFile.writeStub(MetaDataDedupFile.java:397)
        at
org.opendedup.sdfs.io.MetaDataDedupFile.unmarshal(MetaDataDedupFile.java:437)
        at
org.opendedup.sdfs.io.MetaDataDedupFile.sync(MetaDataDedupFile.java:809)
        at fuse.SDFS.SDFSFileSystem.mknod(SDFSFileSystem.java:166)
        at
fuse.Filesystem3ToFuseFSAdapter.mknod(Filesystem3ToFuseFSAdapter.java:119)

After a few thousand errors of the types above, I also got:
12:33:04.262 Thread-891 ERROR [fuse.SDFS.SDFSFileSystem]:
java.lang.ArrayIndexOutOfBoundsException: 11
java.lang.ArrayIndexOutOfBoundsException: 11
        at jdbm.recman.TransactionManager.start(TransactionManager.java:297)
        at jdbm.recman.RecordFile.commit(RecordFile.java:583)
        at jdbm.recman.PageManager.commit(PageManager.java:230)
        at jdbm.recman.BaseRecordManager.commit(BaseRecordManager.java:721)
        at jdbm.recman.CacheRecordManager.commit(CacheRecordManager.java:393)
        at
org.opendedup.sdfs.filestore.MetaFileStore.commit(MetaFileStore.java:171)
        at
org.opendedup.sdfs.filestore.MetaFileStore.setMetaFile(MetaFileStore.java:215)
        at
org.opendedup.sdfs.io.MetaDataDedupFile.unmarshal(MetaDataDedupFile.java:439)
        at
org.opendedup.sdfs.io.MetaDataDedupFile.sync(MetaDataDedupFile.java:809)
        at fuse.SDFS.SDFSFileSystem.mknod(SDFSFileSystem.java:166)
        at
fuse.Filesystem3ToFuseFSAdapter.mknod(Filesystem3ToFuseFSAdapter.java:119)
java.lang.ArrayIndexOutOfBoundsException: 12
        at jdbm.recman.TransactionManager.start(TransactionManager.java:297)
        at jdbm.recman.RecordFile.commit(RecordFile.java:583)
        at jdbm.recman.PageManager.commit(PageManager.java:230)
        at jdbm.recman.BaseRecordManager.commit(BaseRecordManager.java:721)
        at jdbm.recman.CacheRecordManager.commit(CacheRecordManager.java:393)
        at
org.opendedup.sdfs.filestore.MetaFileStore.commit(MetaFileStore.java:171)
        at
org.opendedup.sdfs.filestore.MetaFileStore.setMetaFile(MetaFileStore.java:215)
        at
org.opendedup.sdfs.io.MetaDataDedupFile.unmarshal(MetaDataDedupFile.java:439)
        at
org.opendedup.sdfs.io.MetaDataDedupFile.sync(MetaDataDedupFile.java:809)
        at
org.opendedup.sdfs.io.SparseDedupFile.close(SparseDedupFile.java:499)
        at
org.opendedup.sdfs.io.SparseDedupFile.unRegisterChannel(SparseDedupFile.java:458
)
        at
org.opendedup.sdfs.io.DedupFileChannel.close(DedupFileChannel.java:287)
        at fuse.SDFS.SDFSFileSystem.release(SDFSFileSystem.java:207)
        at
fuse.Filesystem3ToFuseFSAdapter.release(Filesystem3ToFuseFSAdapter.java:338)
[...]

Then:
Mar 30, 2010 1:00:53 PM org.opendedup.mtools.FDisk checkDedupFile
WARNING: map file
/opt/sdfs/sdfs_vol1/ddb/04/0457be4c-df02-44d2-b274-a066cad6da28/0457be4c-df02-44
d2-b274-a066cad6da28.map
is corrupt
Mar 30, 2010 1:01:00 PM org.opendedup.mtools.FDisk checkDedupFile
WARNING: map file
/opt/sdfs/sdfs_vol1/ddb/04/04418e3c-473b-4cb8-8ccf-d07975980898/04418e3c-473b-4c
b8-8ccf-d07975980898.map
is corrupt
[...]

I doubt that mv hold many files open, so I guess SDFS is forgetting to
close them.

  hypatia:/backup/current# ulimit -n
  8192
  hypatia:/backup/current# cat /proc/sys/fs/file-max
  365636
```

Original issue reported on code.google.com by `stur...@gmail.com` on 30 Mar 2010 at 11:27

**Comment by GoogleCodeExporter** [comment]
```
I think this has been fixed take a look at 0.8.12. I will upload this later 
tonight.
```

Original comment by `sam.silv...@gmail.com` on 31 Mar 2010 at 7:08
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
This has been fixed please take a look at version
http://opendedup.googlecode.com/files/sdfs-0.8.12.tar.gz
```

Original comment by `sam.silv...@gmail.com` on 31 Mar 2010 at 9:51

**Comment by GoogleCodeExporter** [comment]
```
I have fixed another aspect of this where MemoryMapped files are not closed
correctly. Will upload fixed binaries shortly.
```

Original comment by `sam.silv...@gmail.com` on 1 Apr 2010 at 6:07
- Changed state: **Fixed**
