### ISSUE TITLE
While Copying new Data to Dedup Filesystem: Fehler 0x80070057: Falscher Parameter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [XianglinLi/opendedup#64]
```
What steps will reproduce the problem?
1. create filesystem with mksdfs --volume-name=Daten --volume-capacity=2TB 
--io-safe-close=false --base-path d:\sdfs
on a 800GB Filesystem with 400GB free
2. mountsdfs -v Daten -m S
3. copy data from D: (except d:\sdfs) to S:

What is the expected output? What do you see instead?
Expected is a copy process which slows down if needed but does not fail.

What version of the product are you using? On what operating system?
Windows 7 Ultimate x64, Patchlevel of 11.4.2015
SDFS Version 1.2.0
RAM: 8GB

Please provide any additional information below.
Log output:
c:\Program Files (x86)\sdfs>mksdfs --volume-name=Daten --volume-capacity=2TB --i
o-safe-close=false --base-path d:\sdfs\
Attempting to create SDFS volume ...
Volume [Daten] created with a capacity of [2TB]
check [C:\Program Files (x86)\sdfs\etc\Daten-volume-cfg.xml] for configuration d
etails if you need to change anything

c:\Program Files (x86)\sdfs>mountsdfs -v Daten -m S
Running SDFS Version 1.2.0
reading config file = C:\Program Files (x86)\sdfs\etc\Daten-volume-cfg.xml
Loading Hashtable Entries
Loading Hashes |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Loaded entries 0
log4j:WARN No appenders could be found for logger (org.quartz.core.SchedulerSign
alerImpl).
log4j:WARN Please initialize the log4j system properly.
-f
S
version = 600
driverVersion = 400
Exception in thread "Thread-8" java.lang.OutOfMemoryError: GC overhead limit exc
eeded
Exception in thread "Thread-0" java.lang.OutOfMemoryError: GC overhead limit exc
eeded
Exception in thread "Thread-38" java.lang.OutOfMemoryError: GC overhead limit ex
ceeded
Exception in thread "Thread-25" java.lang.OutOfMemoryError: GC overhead limit ex
ceeded
Exception in thread "Thread-35" java.lang.OutOfMemoryError: GC overhead limit ex
ceeded
Exception in thread "FileManager-0" java.lang.OutOfMemoryError: GC overhead limi
t exceeded


```

Original issue reported on code.google.com by `claus.c....@gmail.com` on 11 Apr 2015 at 9:08

Attachments:
- [SDFS.png](https://storage.googleapis.com/google-code-attachments/opendedup/issue-64/comment-0/SDFS.png)

**Comment by GoogleCodeExporter** [comment]
```
This issue also occurs with --io-safe-close=true, but takes longer until it 
occurs.
This time, there are no GC or OutOfMemoryError-Messages.
```

Original comment by `claus.c....@gmail.com` on 11 Apr 2015 at 9:34

**Comment by GoogleCodeExporter** [comment]
```
Same operation like in report, but on a system having 24GB of RAM:
Running SDFS Version 1.2.0
reading config file = C:\Program Files (x86)\sdfs\etc\Daten-volume-cfg.xml
Loading Hashtable Entries
Loading Hashes |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Loaded entries 0
Running Consistancy Check on DSE, this may take a while
Scanning DSE |))))))))))))))))))))))))))))))))))))))))))))))))))| 100%

Finished
Succesfully Ran Consistance Check for [0] records, recovered [0]
log4j:WARN No appenders could be found for logger (org.quartz.core.SchedulerSign
alerImpl).
log4j:WARN Please initialize the log4j system properly.
-f
S
version = 600
driverVersion = 400
Exception in thread "Thread-0" java.lang.OutOfMemoryError: Java heap space
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.<init>(UTF8Read
er.java:122)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.createReader
(XMLEntityManager.java:2285)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrent
Entity(XMLEntityManager.java:679)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineD
ocVersion(XMLVersionDetector.java:189)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:799)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(X
ML11Configuration.java:764)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.
java:123)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.
java:237)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Doc
umentBuilderImpl.java:300)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
        at org.opendedup.sdfs.Config.writeSDFSConfigFile(Config.java:396)
        at org.opendedup.sdfs.io.VolumeConfigWriterThread.writeConfig(VolumeConf
igWriterThread.java:47)
        at org.opendedup.sdfs.io.VolumeConfigWriterThread.run(VolumeConfigWriter
Thread.java:29)
        at java.lang.Thread.run(Thread.java:722)
Exception in thread "Thread-8"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler i
n thread "Thread-8"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler i
n thread "QuartzScheduler_QuartzSchedulerThread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler i
n thread "ActionDistributor-2"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler i
n thread "ActionDistributor-1"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler i
n thread "ActionDistributor-0"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler i
n thread "FileManager-0"
```

Original comment by `claus.c....@gmail.com` on 11 Apr 2015 at 12:25
