### ISSUE TITLE
More permission problems and symlink weirdness

### ISSUE THREAD

**Issue by GoogleCodeExporter** [XianglinLi/opendedup#9]
```
SDFS 0.8.12, Debian lenny++.

While mv(1)ing a large tree to a mounted SDFS, I got the following errors:

  mv: cannot create symbolic link
`./andeby/home/mano2805/.kde/socket-andeby': Permission denied
  mv: cannot create symbolic link `./andeby/home/mano2805/.kde/tmp-andeby':
Permission denied
  mv: cannot create symbolic link
`./andeby/home/mano2805/.kde/cache-andeby': Permission denied

Investigating this, I found:

  hypatia:/backup/current# ls -ld andeby/home/mano2805/.kde/tmp-andeby
  ls: cannot access andeby/home/mano2805/.kde/tmp-andeby: Permission denied
  hypatia:/backup/current# ls -ld andeby/home/mano2805/.kde
  drwxr-xr-x 1 2904 627 10240 Nov 23 10:16 andeby/home/mano2805/.kde
  hypatia:/backup/current# ls -l andeby/home/mano2805/.kde/
  ls: cannot access andeby/home/mano2805/.kde/socket-andeby: Permission denied
  ls: cannot access andeby/home/mano2805/.kde/tmp-andeby: Permission denied
  ls: cannot access andeby/home/mano2805/.kde/cache-andeby: Permission denied
  total 1
  drwxr-xr-x 1 2904 627  2048 Nov 23 10:16 Autostart
  d????????? ? ?    ?       ?            ? cache-andeby
  drwxr-xr-x 1 2904 627 12288 Nov 23 10:16 share
  d????????? ? ?    ?       ?            ? socket-andeby
  d????????? ? ?    ?       ?            ? tmp-andeby

Original directory looks like this:

  hypatia:/backup/current# ls -la ../oldcurrent/andeby/home/mano2805/.kde/
  total 16
  drwx------  4 2904 627 4096 Nov 23 10:16 .
  drwx------ 15 2904 627 4096 Nov 23 10:42 ..
  drwx------  2 2904 627 4096 Nov 23 10:16 Autostart
  lrwxrwxrwx  1 2904 627   26 Feb  6 00:39 cache-andeby -> /var/tmp
/kdecache-mano2805
  drwx------  8 2904 627 4096 Nov 23 10:16 share
  lrwxrwxrwx  1 2904 627   21 Feb  6 00:39 socket-andeby ->
/tmp/ksocket-mano2805
  lrwxrwxrwx  1 2904 627   17 Feb  6 00:39 tmp-andeby -> /tmp/kde-mano2805

o The symlinks were not created correctly, looks like weird directories.
o Directory permissions are wrong (should be 700, not 755).
o The links cannot be removed either:

  hypatia:/backup/current# rm andeby/home/mano2805/.kde/socket-andeby
  rm: cannot remove `andeby/home/mano2805/.kde/socket-andeby': Permission 
denied

Log says:

12:56:20.268 Thread-499 ERROR [fuse.SDFS.SDFSFileSystem]: unable to parse
sylink /andeby/home/mano2805/.kde/socket-andeby
java.nio.file.NoSuchFileException:
/backup/sdfs/sdfs_vol1/files/andeby/home/mano2805/.kde/socket-andeby
        at
sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at
sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at
sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at
sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.ja
va:214)
        at
sun.nio.fs.UnixFileAttributeViews$Unix.getAttribute(UnixFileAttributeViews.java:
323)
        at sun.nio.fs.AbstractPath.getAttribute(AbstractPath.java:403)
        at fuse.SDFS.SDFSFileSystem.getattr(SDFSFileSystem.java:123)
        at
fuse.Filesystem3ToFuseFSAdapter.getattr(Filesystem3ToFuseFSAdapter.java:59)
12:56:20.285 Thread-2300 ERROR [fuse.SDFS.SDFSFileSystem]: unable to parse
sylink /andeby/home/mano2805/.kde/tmp-andeby
java.nio.file.NoSuchFileException:
/backup/sdfs/sdfs_vol1/files/andeby/home/mano2805/.kde/tmp-andeby
        at
sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at
sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at
sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at
sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.ja
va:214)
        at
sun.nio.fs.UnixFileAttributeViews$Unix.getAttribute(UnixFileAttributeViews.java:
323)
        at sun.nio.fs.AbstractPath.getAttribute(AbstractPath.java:403)
        at fuse.SDFS.SDFSFileSystem.getattr(SDFSFileSystem.java:123)
        at
fuse.Filesystem3ToFuseFSAdapter.getattr(Filesystem3ToFuseFSAdapter.java:59)

```

Original issue reported on code.google.com by `stur...@gmail.com` on 31 Mar 2010 at 11:08

**Comment by GoogleCodeExporter** [comment]
```
Will take a look at this today.
```

Original comment by `sam.silv...@gmail.com` on 31 Mar 2010 at 4:43
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
I think this has been fixed. I took a much more sane approach to symlinks.

```

Original comment by `sam.silv...@gmail.com` on 31 Mar 2010 at 10:04
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
Hmm..  Not quite there yet.  You should take care when to follow a symlink.  
This is
0.8.13 (log says 0.812, but I dowloaded 0.8.13):

  hypatia:/backup/current# touch -d yesterday /tmp/foo
  hypatia:/backup/current# ln -s /tmp/foo
  hypatia:/backup/current# chown -h fk foo
  hypatia:/backup/current# ls -l foo
  lrw-r--r-- 1 fk root 8192 Mar 31 13:38 foo -> /tmp/foo
  hypatia:/backup/current# ls -l /tmp/foo
  -rw-r--r-- 1 fk root 0 Mar 31 13:38 /tmp/foo
  hypatia:/backup/current# rm /tmp/foo
  hypatia:/backup/current# ls -l foo
  l--------- 1 root root 8192 Jan  1  1970 foo -> /tmp/foo

Looks like most of the inode struct is filled in by the file which the symlink 
is
linked to, not the symlink itself.  Here is from an ext3 filesystem:

  hypatia:/backup# touch -d yesterday /tmp/foo
  hypatia:/backup# ln -s /tmp/foo
  hypatia:/backup# chown -h fk foo
  hypatia:/backup# ls -l foo
  lrwxrwxrwx 1 fk root 8 Apr  1 13:41 foo -> /tmp/foo
  hypatia:/backup# ls -l /tmp/foo
  -rw-r--r-- 1 root root 0 Mar 31 13:41 /tmp/foo
  hypatia:/backup# rm /tmp/foo
  hypatia:/backup# ls -l foo
  lrwxrwxrwx 1 fk root 8 Apr  1 13:41 foo -> /tmp/foo

The symlink has it's own mode (meaningless), owner, group, [acm]time, etc.

Now I will have to check that none of the symlinks I moved to the SDFS points to
important system files.  mv will happily change the owner of a symlink pointing 
to
/etc/shadow to whoever owned the original symlink.  In the case of SDFS it will
change the owner of the file the symlink points to.  Not good.
```

Original comment by `stur...@gmail.com` on 1 Apr 2010 at 11:48

**Comment by GoogleCodeExporter** [comment]
```
Thanks sturles,

Let me take another look at this.
```

Original comment by `sam.silv...@gmail.com` on 2 Apr 2010 at 5:07
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
fixed in 0.8.15 release
```

Original comment by `sam.silv...@gmail.com` on 9 Apr 2010 at 4:50
- Changed state: **Verified**

**Comment by GoogleCodeExporter** [comment]
```
Not entirely.  Here (SDFS 0.8.15) I try to change the ownership of the symlink 
bar to
fk, but sdfs still follows to the file foo and fails when foo does not exist.  
If foo
exists, the ownership of foo is changed, not bar.  Note the -h option to chown
(affect each symbolic link instead of any referenced file):

hypatia:/backup/current# ln -s foo bar
hypatia:/backup/current# chown -h fk bar
chown: changing ownership of `bar': No such file or directory
hypatia:/backup/current# touch foo
hypatia:/backup/current# chown -h fk bar
hypatia:/backup/current# ls -l foo bar
lrwxrwxrwx  1 root root 3 Apr 15 13:10 bar -> foo
-rw-r--r--. 1 fk   root 0 Apr 15 13:10 foo

```

Original comment by `stur...@gmail.com` on 15 Apr 2010 at 11:17

**Comment by GoogleCodeExporter** [comment]
```
"Permission Denied" and "Could not find" errors in the latest version too


What steps will reproduce the problem?
1. make and mount SDFS Filesystem.
2. Copy Source data on to it using. CD to the source directory then
  find . -print -depth | cpio  -pdm "path to mounted SDFS filesytem"


What is the expected output? What do you see instead?

Following is what i get, where the copy is going on

cpio: ../nntp.tc: Cannot create symlink to
`/mnt/sdfs/source_dedup//./100217.0300.FAILED/grad/project/disco/xk/lib/tcplib/l
inux-alpha/nntp.tc':
Permission denied
cpio: ../phone.tc: Cannot create symlink to
`/mnt/sdfs/source_dedup//./100217.0300.FAILED/grad/project/disco/xk/lib/tcplib/l
inux-alpha/phone.tc':
Permission denied
cpio: ../sample.tc: Cannot create symlink to
`/mnt/sdfs/source_dedup//./100217.0300.FAILED/grad/project/disco/xk/lib/tcplib/l
inux-alpha/sample.tc':
Permission denied
cpio: ../smtp.tc: Cannot create symlink to
`/mnt/sdfs/source_dedup//./100217.0300.FAILED/grad/project/disco/xk/lib/tcplib/l
inux-alpha/smtp.tc':
Permission denied
cpio: ../telnet.tc: Cannot create symlink to
`/mnt/sdfs/source_dedup//./100217.0300.FAILED/grad/project/disco/xk/lib/tcplib/l
inux-alpha/telnet.tc':
Permission denied
cpio: ../nntp.tc: Cannot create symlink to
`/mnt/sdfs/source_dedup//./100217.0300.FAILED/grad/project/disco/xk/lib/tcplib/l
inux-x86/nntp.tc':
Permission denied

Following is what the SDFS logs say:
13:50:17.853 Thread-330770  INFO [fuse.SDFS.SDFSFileSystem]: could not find
/mnt/sdfs/files/100217.0300.FAILED/grad/project/pupala/ns-2.1b5/tk8.0.4/tests/wi
ndow.test
13:50:17.854 Thread-330994  INFO [fuse.SDFS.SDFSFileSystem]: could not find
/mnt/sdfs/files/100217.0300.FAILED/grad/project/pupala/ns-2.1b5/tk8.0.4/tests/wi
ndow.test
13:50:17.859 Thread-330770  INFO [fuse.SDFS.SDFSFileSystem]: could not find
/mnt/sdfs/files/100217.0300.FAILED/grad/project/pupala/ns-2.1b5/tk8.0.4/tests/wi
nfo.test
13:50:17.859 Thread-330994  INFO [fuse.SDFS.SDFSFileSystem]: could not find
/mnt/sdfs/files/100217.0300.FAILED/grad/project/pupala/ns-2.1b5/tk8.0.4/tests/wi
nfo.test
13:50:17.868 Thread-330922  INFO [fuse.SDFS.SDFSFileSystem]: could not find
/mnt/sdfs/files/100217.0300.FAILED/grad/project/pupala/ns-2.1b5/tk8.0.4/unix
13:50:17.868 Thread-331446  INFO [fuse.SDFS.SDFSFileSystem]: could not find
/mnt/sdfs/files/100217.0300.FAILED/grad/project/pupala/ns-2.1b5/tk8.0.4/unix
13:50:17.869 Thread-331437  INFO [fuse.SDFS.SDFSFileSystem]: could not find
/mnt/sdfs/files/100217.0300.FAILED/grad/project/pupala/ns-2.1b5/tk8.0.4/unix




What version of the product are you using? On what operating system?
The Latest one SDFS 0.9.2 

Please provide any additional information below.
```

Original comment by `sonu.iq...@gmail.com` on 25 May 2010 at 5:51
